apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: vue
  name: vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
      - image: mjhea0/vue-kubernetes:latest
        imagePullPolicy: Always
        name: vue
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "512Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
